name: ProxyIP Checking Tool

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */6 * * *'

jobs:
  scan-proxies:
    runs-on: ubuntu-26.04
    name: 🌀 Checking Proxies

    steps:
    - name: 🪟 Checkout Repository
      uses: actions/checkout@v7

    - name: ⚙️ Setup GoLang 
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: 🌎 Run Checker
      env: 
        WORKER_URLS: ${{ secrets.WORKER_URLS }}
      run: |
        go run main.go

    - name: 📥 Commit Results
      if: success()
      run: |
        git config --global user.name "NET-Sentinel Bot"
        git config --global user.email "224584266+NetSentinel-Bot@users.noreply.github.com"
        git add Data/alive.txt
        git commit -m "🪟 Proxies successfully updated." || echo "No changes to commit"
        git push origin main
